export const blogPosts = [
  {
    _id: "1",
    title: "What do you want to know about UI",
    author: "Tom Hank",
    role: "Creative Director",
    image: "/01.png",
    avatar: "/02.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "2",
    title: "All the features you want to know",
    author: "Arthur Melo",
    role: "Creative Director",
    image: "/02.png",
    avatar: "/01.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "3",
    title: "Which services you get from Meraki UI",
    author: "Amelia Anderson",
    role: "Lead Developer",
    image: "/02.png",
    avatar: "/01.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "4",
    title: "How to improve your UX skills",
    author: "Jake Peralta",
    role: "UI/UX Designer",
    image: "/04.png",
    avatar: "/03.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "5",
    title: "Best practices for frontend development",
    author: "Amy Santiago",
    role: "Senior Frontend Developer",
    image: "/03.png",
    avatar: "/05.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "6",
    title: "Why design systems matter",
    author: "Rosa Diaz",
    role: "Design Lead",
    image: "/06.png",
    avatar: "/02.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "7",
    title: "Accessibility in modern web apps",
    author: "Charles Boyle",
    role: "Web Accessibility Expert",
    image: "/01.png",
    avatar: "/04.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "8",
    title: "The future of AI in UI design",
    author: "Terry Jeffords",
    role: "AI Researcher",
    image: "/05.png",
    avatar: "/06.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
  {
    _id: "9",
    title: "Understanding micro-interactions",
    author: "Gina Linetti",
    role: "Creative Strategist",
    image: "/07.png",
    avatar: "/08.png",
    excerpt: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium.",
  },
];
